language: node_js
node_js:
  - 12.18.4

before_install:
  - npm install -g hexo-cli
  - hexo init blog
  - npm i hexo-generator-json-content --save
  - npm install  hexo-deployer-git --save

install:
    - ls
    - mv sourcce blog
    - mv themes blog
    - mv _config.yml blog
    - mv README.md blog
    - ls blog
    - cd blog
    - npm un hexo-renderer-marked --save
    - npm i hexo-renderer-markdown-it --save
    - hexo g
#    - hexo d
#    - npm install
#    - bower install
#script:
#    - ember test --server
