language: node_js
node_js:
  - 12.18.4

before_install:
  - npm install -g hexo-cli
  - hexo init


install:
    - ls
    - npm i hexo-generator-json-content --save
    - npm install  hexo-deployer-git --save
    - npm un hexo-renderer-marked --save
    - npm i hexo-renderer-markdown-it --save
    # 生成配置
    - hexo clean
    - hexo g
    - ls -lha public
#    - hexo d
#    - npm install
#    - bower install
script:
  - ls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: md
    target_branch: gh-pages
