language: node_js
node_js:
  - 12.18.4

before_install:
  - npm install -g hexo-cli
  - hexo init blog
  - npm un hexo-renderer-marked --save
  - npm i hexo-renderer-markdown-it --save
  - npm i hexo-generator-json-content --save
  - npm install  hexo-deployer-git --save

install:
    - mv dollarser.github.io/sourcce blog
    - mv dollarser.github.io/themes blog
    - mv dollarser.github.io/_config.yml blog
    - mv dollarser.github.io/README.md blog
    - ls blog
    - hexo g
    - hexo d
#    - npm install
#    - bower install
#script:
#    - ember test --server
