language: node_js
node_js:
  - 12.18.4

before_install:
  - npm install -g hexo-cli
  - hexo init blog


install:
    - ls
    - ls blog
    # 删除文件
    - rm -r blog/source blog/themes blog/_config.yml
    # copy文件
    - mv source blog
    - mv themes blog
    - mv _config.yml blog
    - mv README.md blog
    # 安装依赖
    - cd blog
    - npm i hexo-generator-json-content --save
    - npm install  hexo-deployer-git --save
    - npm un hexo-renderer-marked --save
    - npm i hexo-renderer-markdown-it --save
    # 生成配置
    - hexo g
#    - hexo d
#    - npm install
#    - bower install
#script:
#    - ember test --server
