language: node_js
node_js:
  - 12.18.4
nvm:
  - 3.6.3

before_install:
  - npm install -g hexo-cli
  - hexo init blog

install:
    - ls
    - ls blog
    # 删除文件
    - rm -r blog/source blog/themes
    - rm -r blog/_config.yml
    # copy文件
    - cp -r source blog
    - cp -r themes blog
    - cp -r _config.yml blog

    # 安装依赖
    - cd blog
    - npm ls --depth 0
    
    #- npm i urix --save
    # - npm i resolve-url --save
    # - npm i urix --save
    # - npm i urix --save
    
    # - npm i hexo-generator-json-content --save
    # - npm install  hexo-deployer-git --save
    # - npm un hexo-renderer-marked --save
    # - npm i hexo-renderer-markdown-it --save
    - npm ls --depth
    # 生成配置
    - hexo clean
    - hexo g --debug
    - ls -lha public
    # - hexo d

script:
  - ls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: blog/public
  keep-history: true
  on:
    branch: md
    target_branch: gh-pages
